[package]
name = "delmat"
version = "0.1.0"
edition = "2021"

[dependencies]
candle = "0.2"
tch = { version = "0.7", features = ["cuda"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokenizers = "0.13"
anyhow = "1.0"
tensorrt-rs = "0.1"
